name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  statuses: write

jobs:
  release:
    uses: neoforged/actions/.github/workflows/gradle-publish.yml@main
    with:
      java: ${ jdkVersion in ['8', '11', '17'] ? jdkVersion : '17' }
      pre_gradle_tasks: ${ project.tasks.findByName('test')?.enabled ? 'test' : "''" }
      gradle_tasks: publish ${ project.plugins.hasPlugin('io.github.gradle-nexus.publish-plugin') ? 'closeAndReleaseSonatypeStagingRepository' : '' }
    secrets:
      DISCORD_WEBHOOK: \${{ secrets.DISCORD_WEBHOOK }}
      MAVEN_USER: \${{ secrets.MAVEN_USER }}
      MAVEN_PASSWORD: \${{ secrets.MAVEN_PASSWORD }}
      GPG_PRIVATE_KEY: \${{ secrets.GPG_PRIVATE_KEY }}
      GPG_KEY_PASSWORD: \${{ secrets.GPG_KEY_PASSWORD }}
      <% out << (project.plugins.hasPlugin('io.github.gradle-nexus.publish-plugin') ? "SONATYPE_USER: \${{ secrets.SONATYPE_USER }}\n      SONATYPE_PASSWORD: \${{ secrets.SONATYPE_PASSWORD }}" : '') %>